global using System.Net;
global using System.Net.Mime;
global using Bogus;
global using Microsoft.AspNetCore.Mvc;
global using Weather.Api.Models.Dtos;
global using Weather.Api.Models.Request;
global using Weather.Api.Models.Response;
global using Weather.Api.Services;
global using Weather.Api.Services.Interfaces;
